version: '3.5'

services:

  consul:
    image: consul:1.8.0
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net

  mysql-standalone:
    image: mysql:5.6
    networks:
      - consul-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kladr
      - MYSQL_USER=kladr
      - MYSQL_PASSWORD=kladr

  service-database:
    restart: on-failure
    build:
      context: service-database
      dockerfile: docker/DockerFile
    ports:
      - "7000-7005:7000"
    networks:
      - consul-net
    depends_on:
      - mysql-standalone

  service-dadata:
    restart: on-failure
    build:
      context: service-dadata
      dockerfile: docker/DockerFile
    ports:
      - "7006-7010:7000"
    networks:
      - consul-net

  service-route:
    restart: on-failure
    build:
      context: service-route
      dockerfile: docker/DockerFile
    ports:
      - "7020:7000"
    networks:
      - consul-net

  service-gateway:
    restart: on-failure
    build:
      context: service-gateway
      dockerfile: docker/DockerFile
    ports:
      - "7030:7000"
    networks:
      - consul-net
    depends_on:
      - mysql-standalone
      - service-database
      - service-dadata
      - service-route


networks:
  consul-net:
    driver: bridge
