spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: dadata-service
          uri: lb://dadata-service
          predicates:
            - Path=/dadata/**
          filters:
            - RewritePath=/dadata/(?<path>.*), /$\{path}
        - id: customer-service
          uri: lb://database-service
          predicates:
            - Path=/database/**
          filters:
            - RewritePath=/database/(?<path>.*), /$\{path}

logging.level.com.netflix: DEBUG
    
management:
  security:
    enabled: false