server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: databaseModule
          uri: http://localhost:8092/
          predicates:
            - Path=/database/**
        - id: dadataModule
          uri: http://localhost:8091/
          predicates:
            - Path=/consumer/**