spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
#    url: jdbc:mysql://localhost:3306/kladr?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: kladr
#    password: kladr
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : update
    properties:
      hibernate.dialect : org.hibernate.dialect.H2Dialect

  #      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  application:
    name: database-service

  output.ansi.enabled: ALWAYS

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

#---
#spring:
#  profiles: zone1
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone1
#
#---
#spring:
#  profiles: zone2
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone2