spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-dadata
          uri: lb://service-dadata
          predicates:
            - Path=/dadata/**
          filters:
            - RewritePath=/dadata/(?<path>.*), /$\{path}
        - id: service-database
          uri: lb://service-database
          predicates:
            - Path=/database/**
          filters:
            - RewritePath=/database/(?<path>.*), /$\{path}
        - id: service-route
          uri: lb://service-route
          predicates:
            - Path=/kladr/**
          filters:
            - RewritePath=/kladr/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
    org.springframework:
      cloud.consul: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


