spring:  
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-dadata
          uri: lb://service-dadata
          predicates:
            - Path=/dadata/**
          filters:
            - RewritePath=/dadata/(?<path>.*), /$\{path}
        - id: service-database
          uri: lb://service-database
          predicates:
            - Path=/database/**
          filters:
            - RewritePath=/database/(?<path>.*), /$\{path}
        - id: service-route
          uri: lb://service-route
          predicates:
            - Path=/kladr/**
          filters:
            - RewritePath=/kladr/(?<path>.*), /$\{path}


logging.level.com.netflix: DEBUG
    
management:
  security:
    enabled: false