spring:  
  application:
    name: dadata-service

  output.ansi.enabled: ALWAYS

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

#---
#spring:
#  profiles: zone1
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone1
#
#---
#spring:
#  profiles: zone2
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone2